### ISSUE TITLE
Включить тёмные стандартные скроллбары в тёмных темах

### ISSUE THREAD

**Issue by murphyne** [serguun42/OsnovaDarkTheme#2]
Стандартные скроллбары должны менять цвет в&nbsp;зависимости от&nbsp;выбранной темы: в&nbsp;светлых темах&nbsp;&mdash; светлые скроллбары, в&nbsp;тёмных темах&nbsp;&mdash; тёмные скроллбары. Сейчас стандартные скроллбары остаются светлыми даже в&nbsp;тёмных темах.

Включить тёмные скроллбары можно так:

```css
:root {
  color-scheme: dark;
}
```

Применил код выше с&nbsp;помощью [Stylus](https://add0n.com/stylus.html) на&nbsp;стандартной тёмной теме, конфликтов с&nbsp;другими элементами не&nbsp;заметил.

Ссылки по&nbsp;теме:

- [Пример сайта с&nbsp;тёмными скроллбарами](https://developer.mozilla.org/en-US/docs/Web)
- [Документация по&nbsp;свойству `color-scheme` на&nbsp;MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)
- [Ответ про&nbsp;свойство `color-scheme` на&nbsp;StackOverflow](https://stackoverflow.com/q/65940522)

**Comment by serguun42** [comment]
Добавил это свойство в корневую тёмную тему. Теперь во всех тёмных темах при этой включённой опции полосы прокрутки тёмные. Уже на проде!
