### ISSUE TITLE
Не совместимо с новым "редизайном" Основы

### ISSUE THREAD

**Issue by rockenren** [serguun42/OsnovaDarkTheme#3]
Сильно не надеюсь конечно, но текущая версия уже несовместима с новым "редизайном" Основы, который Комитет недавно выпустил в прод, пока что на DTF. Скрипт полностью ломает десктопную версию и просто не работает в мобильной (Safari iOS).

На VC.RU еще работает, как в десктопной, так и мобильной версиях.

Как теперь жить?

**Comment by serguun42** [comment]
Да, всё так. Ломает, как и другие мои скрипты (например, расширение кэшера имён).

Сейчас в планах нет рефакторинга тем на редизайн-версию. По крайней мере, пока доступен старый дизайн. В 2024, когда старый дизайн полностью отключат, уже стоит начать шевелиться – если запрос ещё будет и если Комитет не отключит свои площадки 😅

Пока жить предлагаю на старом дизайне – и тут не только в темах дело. При использовании редизайна просто отключи юзер-скрипты в своём *monkey.

**Comment by rockenren** [comment]
Всё, VC.RU тоже отправился в страну Вечных Редизайнов(ТМ).
Еще раз спасибо спасибо.
